/// Flutter icons IconPack
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconPack
///      fonts:
///       - asset: fonts/IconPack.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconPack {
  IconPack._();

  static const _kFontFam = 'IconPack';

  static const IconData move_task = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData task_list = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData question = const IconData(0xe802, fontFamily: _kFontFam);
}
